[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.24'
libs = ["lib"]
evm_version = 'london'
via_ir = true

[profile.flareTest]
rpc_url = 'https://coston2-api.flare.network/ext/C/rpc'
chain_id = 114





