[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.24'
libs = ["lib"]
evm_version = 'cancun'
via_ir = true

[dependencies]
flare-foundry-periphery-package = { path = "./lib/flare-foundry-periphery-package" }
